version: '2'

services:
  nginx:
    build: ./nginx
    links:
      - service1:service1
    ports:
      - "80:80"
  service1:
    image: node:7.5.0
    volumes:
      - ./service1:/app
    links:
      - redis
    ports:
      - "8080:8080"
    working_dir: "/app"
    command: npm start
  redis:
    image: redis
    ports:
        - "6379"
