version: '2'

services:

  nginx:
    build: ./nginx
    links:
      - notes:notes
      - search:search
    ports:
      - "80:80"

  redis:
    image: redis
    ports:
      - "6379"

  mongo:
    build: ./mongo
    expose:
      - "27017"
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/var/lib/mongodb

  notes:
    image: node:7.5.0
    volumes:
      - ./notes:/app
    links:
      - redis
      - mongo
    working_dir: "/app"
    command: npm start

  search:
    image: node:7.5.0
    volumes:
      - ./search:/app
    links:
      - redis
      - mongo
    working_dir: "/app"
    command: npm start
